### ISSUE TITLE
Bruting with plain IP list

### ISSUE THREAD

**Issue by InvisibleRagman** [inkarnadin/alarh-camera-scanner#5]
Hi, many thanks for your work!

I have an issue, when i want to brute (without scanning) from a plain ip list:

java -jar /home/ragman/alarh-camera-scanner/target/camera-scanner-0.5.1.jar -nc -source:ips.txt -passwords:creds.txt -sf
Started...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at scanner.http.ip.IpV4AddressRange.<init>(IpV4AddressRange.java:56)
	at scanner.http.ip.RangeUtils.prepare(RangeUtils.java:41)
	at scanner.runner.Runner.run(Runner.java:55)
	at scanner.Main.main(Main.java:16)

I think the tool is searching for an ip range, not for single ips. Can you solve the problem? Maybe it's my fault for sure.

Rag

**Comment by inkarnadin** [comment]
Hello!
Unfortunately, some of the functionality has been broken in the latest versions. Versions [0.5.0](https://github.com/inkarnadin/alarh-camera-scanner/releases/tag/v0.5.0) and [0.5.1](https://github.com/inkarnadin/alarh-camera-scanner/releases/tag/v0.5.1) may behave incorrectly in some cases - this functionality will be revised in the future.

You can use an earlier version (for example, [0.4.0](https://github.com/inkarnadin/alarh-camera-scanner/releases/tag/v0.4.0)) to correctly scan against a list of addresses (instead range).

Thanks for the feedback, it's very important to me!

**Comment by InvisibleRagman** [comment]
Thank you for your quick reply! 

I can't find any .jar file in the 0.4.0 version, does this version run differently?

**Comment by inkarnadin** [comment]
These are the sources of the specified version.
[Added compiled file in assets.](https://github.com/inkarnadin/alarh-camera-scanner/releases/tag/v0.4.0)
